# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcinit < Formula
  desc "Cross-platform Minecraft developer server management tool"
  homepage "https://github.com/jackh54/mcinit"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jackh54/mcinit/releases/download/v0.1.0/mcinit_0.1.0_darwin_amd64.tar.gz"
      sha256 "aede46143b36a5365b6b8e98243d99cc46a6e1da4bbaad09eeca02577d54a44a"

      def install
        bin.install "mcinit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jackh54/mcinit/releases/download/v0.1.0/mcinit_0.1.0_darwin_arm64.tar.gz"
      sha256 "fc90563b9578eda49942a1e4da7d3ff3120cb71143c434dce6b7b5b49ea555c3"

      def install
        bin.install "mcinit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackh54/mcinit/releases/download/v0.1.0/mcinit_0.1.0_linux_amd64.tar.gz"
      sha256 "573749de87fc7b31ba79c4a9926fdd6daafd2bdc8a2e438230e24d43ee4313fb"
      def install
        bin.install "mcinit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackh54/mcinit/releases/download/v0.1.0/mcinit_0.1.0_linux_arm64.tar.gz"
      sha256 "f21bf8999f8d669f24881366c708846f4e7cf7777a5b6a7670260b9edf7caf54"
      def install
        bin.install "mcinit"
      end
    end
  end

  test do
    system "#{bin}/mcinit --version"
  end
end
